[package]
name = "arms"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
tera = "1.5.0"
serde = "1.0"
dotenv = "0.15.0"
diesel = { version = "1.4.4", features = ["postgres"] }
actix-identity = "0.3.1"
